// simple-bench/vue-list/src/App.vue
<script setup>
import { ref, nextTick } from 'vue';
import { buildRows, resetIds } from '../../shared/data.js';

const rows = ref([]);
const selectedId = ref(-1);

window.__simpleBench = {
  ready: true,
  async run(n) { resetIds(); selectedId.value = -1; rows.value = buildRows(n); await nextTick(); },
  async append(n) { rows.value = rows.value.concat(buildRows(n)); await nextTick(); },
  async updateEvery10th() {
    const next = rows.value.slice();
    for (let i = 0; i < next.length; i += 10) next[i] = { ...next[i], label: next[i].label + ' !!!' };
    rows.value = next;
    await nextTick();
  },
  async select(i) { selectedId.value = rows.value[i]?.id ?? -1; await nextTick(); },
  async swap() {
    if (rows.value.length < 999) return;
    const next = rows.value.slice();
    const a = next[1]; next[1] = next[next.length - 2]; next[next.length - 2] = a;
    rows.value = next;
    await nextTick();
  },
  async remove(i) { rows.value = rows.value.filter((_, k) => k !== i); await nextTick(); },
  async clear() { rows.value = []; selectedId.value = -1; await nextTick(); },
  count() { return rows.value.length; }
};
</script>

<template>
  <table><tbody>
    <tr v-for="row in rows" :key="row.id" :class="row.id === selectedId ? 'selected' : ''">
      <td>{{ row.id }}</td><td>{{ row.label }}</td>
    </tr>
  </tbody></table>
</template>

// simple-bench/svelte-list/src/App.svelte
<script>
  import { flushSync } from 'svelte';
  import { buildRows, resetIds } from '../../shared/data.js';

  let rows = $state([]);
  let selected = $state(-1);

  const api = {
    ready: true,
    run(n) { flushSync(() => { resetIds(); selected = -1; rows = buildRows(n); }); },
    append(n) { flushSync(() => { rows = rows.concat(buildRows(n)); }); },
    updateEvery10th() {
      flushSync(() => {
        for (let i = 0; i < rows.length; i += 10) {
          rows[i] = { ...rows[i], label: rows[i].label + ' !!!' };
        }
      });
    },
    select(i) { flushSync(() => { selected = i; }); },
    swap() {
      flushSync(() => {
        if (rows.length < 999) return;
        const a = rows[1]; rows[1] = rows[rows.length - 2]; rows[rows.length - 2] = a;
      });
    },
    remove(i) { flushSync(() => { rows = rows.filter((_, k) => k !== i); }); },
    clear() { flushSync(() => { rows = []; selected = -1; }); },
    count() { return rows.length; }
  };
  window.__simpleBench = api;
</script>

<table>
  <tbody>
    {#each rows as row, i (row.id)}
      <tr class={i === selected ? 'selected' : ''}>
        <td>{row.id}</td><td>{row.label}</td>
      </tr>
    {/each}
  </tbody>
</table>
